export const STATUS: string[] = ["In Progress", "Completed", "Postponed"];

export const GENRE: string[] = [
  "Action",
  "Adventure",
  "Comedy",
  "Drama",
  "Josei",
  "Manga",
  "Manhua",
  "Manhwa",
  "Mystery",
  "Romance",
  "School Life",
  "Sci-fi",
  "Shoujo",
  "Shounen",
  "Slice of Life",
  "Tragedy",
  "Fantasy",
  "Historical",
  "Gender Bender",
  "Harem",
  "Martial Arts",
  "Mecha",
  "Psychological",
  "Horror",
  "Comic",
];
